version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "php artisan migrate && php artisan serve --host=0.0.0.0"
    depends_on: 
      - db
    restart: on-failure
    ports: 
      - "8000:8000"
    links: 
      - "db"

  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipe
      MYSQL_USER: recipe
      MYSQL_PASSWORD: recipe
  
volumes:
  mysql-data:
